/* CS++
 * PROGRAMMING CHALLENGE 2: ADVANCED
 * GIVEN AN ARRAY OF INTEGERS, RETURN AN ARRAY WHERE THE PRODUCT OF THE FIRST TWO ELEMENTS IS THE THIRD
 *
 * NOTE: IF THERE ARE MORE THAN ONE SETS OF NUMBERS WHICH SATISFY THIS CONDITION, RETURN THE FIRST
 *
 * EXAMPLE: 
 *	
 * INPUT = [4,2,9,7,54,2,9,18]
 * RESULT = [9,7,63]
 *
 */

int *prodArray(int input[],int len)
{
}
