/* CS++
 * PROGRAMMING CHALLENGE 2: BEGINNER
 *
 * GIVEN AN ARRAY OF INTEGERS, RETURN AN ARRAY WHICH CONTAINS THE HIGHEST AND LOWEST VALUE
 *
 * EXAMPLE:
 * INPUT = [1,3,6,93,1,1,-2,50]
 * RESULT = [-2,93]
 */

int *highLow(int input[],int len)
{
}
